# "local" 환경에서 H2 DB 사용
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  sql:
    init:
      mode: embedded # default가 embedded
  h2:
    console:
      enabled: true
