spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true # ?? ??? ??? ??? ???? ?? ?? logging? ??
        format_sql: true #sql format ???
        highlight_sql: true #sql ????
        use_sql_comments: true #???? ???? ? ??
    open-in-view: true # ?? OSIV https://livelyoneweek.tistory.com/57, https://velog.io/@dnwlsrla40/JPA-Open-In-View

logging:
  level:
    org:
      hibernate:
        SQL: debug # ?? ??? ??? ??? ????? ? spring jpa properties? ??? ?? logging? ???? ??.
        orm:
          jdbc:
            bind: trace #sql ? binding parameter?? ?? ????
    springframework: # Security ?? ???? ???? ?? ??
      security: debug
