drop table if exists app_user cascade;

create table app_user
(
    id                bigint generated by default as identity,
    username          varchar(10) not null,
    password          varchar(511) not null,
    primary key (id)
);